//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabemashou_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishesPerLocal
    {
        public int IdLocal { get; set; }
        public int IdDish { get; set; }
        public bool State { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Local Local { get; set; }
    }
}
