//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabemashou_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public decimal IdCard { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int Nationality { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string SecondLastName { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Country Country { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
