//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabemashou_User.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishesByCheck
    {
        public decimal UnitaryPrice { get; set; }
        public decimal Quantity { get; set; }
        public decimal SellTax { get; set; }
        public decimal ServiceTax { get; set; }
        public int IdDish { get; set; }
        public int IdCheck { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Dish Dish { get; set; }

        public decimal getTotal()
        {
            return (UnitaryPrice + (UnitaryPrice * SellTax / 100) + (UnitaryPrice * ServiceTax / 100)) * Quantity;
        }
    }
}
