//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabemashou_User.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishesByCheck
    {
        public decimal UnitaryPrice { get; set; }
        public decimal Quantity { get; set; }
        public decimal SellTax { get; set; }
        public decimal ServiceTax { get; set; }
        public int IdDish { get; set; }
        public int IdCheck { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Dish Dish { get; set; }

        public decimal getTotal()
        {
            return (UnitaryPrice + (UnitaryPrice * SellTax / 100) + (UnitaryPrice * ServiceTax / 100)) * Quantity;
        }
    }
}
