//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabemashou_User.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentByCustomer
    {
        public decimal IdCard { get; set; }
        public int IdCheck { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
