//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabemashou_User.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentByCustomer
    {
        public decimal IdCard { get; set; }
        public decimal AccountNumber { get; set; }
        public int IdCheck { get; set; }
        public System.DateTime Date { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
